### ISSUE TITLE
about pittsburgh250k-P2E dataset & YQ360

### ISSUE THREAD

**Issue by jinxxo-j** [zafirshi/PanoVPR#1]
Hello!
I am very interested in your paper and code 
Thanks for your research! 

I have some question about your paper, especially the datasets.

1. Can you find the heading angle for the query image and database image of the Pittsburgh250k-P2E dataset?
2. Similarly, is it possible to know the heading angle for the query image and database image of the YQ360 dataset?

Thanks again for your interesting research.

**Comment by zafirshi** [comment]
Hi, thank you for your interest in our work! 😄 

The answer to both questions is the same: **No**. That is, PanoVPR cannot determine the orientation angle of the perspective query images within the matching location on the panoramic images, and this applies not only to the Pitts250K-P2E dataset but also to the YQ360 dataset.

In our method, the perspective query images are retrieved by searching through multiple panoramic sub-windows without any orientation angle information. Additionally, the Pitts250K-P2E and YQ360 datasets do not include ground truth labels for orientation information during their collection and production.

I hope my answer has addressed your question. If you have any other questions, feel free to ask.
