### ISSUE TITLE
Some questions for dataset

### ISSUE THREAD

**Issue by jinxxo-j** [zafirshi/PanoVPR#2]
Thanks for your interesting research!

I am looking to do a project based on this research and have two questions regarding it.
1. what PAL camera did you use to create YQ360 dataset?
2. what code did you use to unfold the sphere-like image obtained through the PAL camera into an equirectangular image? Can you share?

**Comment by zafirshi** [comment]
Thank you for your interest in our work, and I apologize for the time gap before answering your question!

1. The PAL camera is a ready-made camera designed and manufactured by our research group's optical design experts.

2. The script for panoramic image unfolding is unfortunately missing. 😭  For the panoramic ringband images at our work, I implement this using the direct unfolding method of _symmetrically unfolding the inner and outer circle radius,_ i.e., the average of the inner and outer radius is used as the length of the unfolded rectangular map, stretching the inner diameter portion upward and compressing the outer diameter portion downward.

I hope my answer clears up your confusion.
