### ISSUE TITLE
some question about code

### ISSUE THREAD

**Issue by jinxxo-j** [zafirshi/PanoVPR#3]
hello.
I have a question about code.
If I change only the backbone to resnet18 for that model and proceed with the training, the 
LOSS is NAN as shown below, will it be solved if I train with less than the default LR value of 0.00001?

**Comment by zafirshi** [comment]
You can try to change the LR rate，deep learning methods require tuning training parameters for different models.

Also, adjust `cache_refresh_rate` and `queries_per_epoch` may be helpful！😄
