### ISSUE TITLE
about Pittsburgh250k-P2E

### ISSUE THREAD

**Issue by jinxxo-j** [zafirshi/PanoVPR#4]
Hello! 

I would like to re-download the Pittsburgh250K-P2E dataset,
but it says the one drive link has expired.... Is it possible to download it again through one drive?
I can't use baidu, so please help!

**Comment by jinxxo-j** [comment]
Additionally, I would like to confirm that the number of train-queries_split images for pittsburgh250k-p2e I received is 3912, while the number of train-queries_split images in the paper is 2940.

**Comment by zafirshi** [comment]
The statistics of the `queries_split` value in the Pitts250K-P2E in the paper is indeed a clerical error, the actual value should be **3912**, not **2940**. The division of the dataset and the quantity of each part, based on open-source datasets.

The OneDrive link for the dataset has been updated！ 🎉 

Thank you!
