### ISSUE TITLE
About pretrained model

### ISSUE THREAD

**Issue by zcyverysix** [zafirshi/PanoVPR#5]
@zafirshi @elnino9ykl @MasterHow 
Hi, I am very interested in your work and code. Thanks for your inspiring reserach.
I would like to download the pretrained model on the pitts250k and yq360 for the inference process. Is there the download link? 
Please help me , thanks a lot!

**Comment by zafirshi** [comment]
Thank you very much for your interest in our work！ 😄 

The pre-trained model weights for PanoVPR will not be made public for now. You can get them in the `logs` folder after running the `train.py` file.

Of course, as mentioned in [issue#3](https://github.com/zafirshi/PanoVPR/issues/3#issuecomment-1985437596), you will need to tune the parameters for different framework configurations.
